spring:
  application:
    name: order-manage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_manage
    username: root
    password: 123456
  profiles:
    active: dev


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    chaye.com.ordermanage: debug
    org.springframework.web: info

server:
  port: 8080
  servlet:
    context-path: /api
